spring:
#  data source connection settings using h2
  datasource:
    url: 'jdbc:h2:mem:testdb;NON_KEYWORDS=USER;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: sa
    driver-class: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: default
#  jpa:
#    defer-datasource-initialization: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
